### ISSUE TITLE
[Enhancement] Change the player's entity name.

### ISSUE THREAD

**Issue by AnOpenSauceDev** [Patbox/StyledNicknames#13]
While the mod changes the player's display name, the name above the player itself does not change, which sort of defeats the whole purpose of changing your in-game name.

**Comment by Patbox** [comment]
That wouldn't solve it, as nicknames aren't synced with client

**Comment by n1ckoates** [comment]
Any chance this could be done by hiding the vanilla display name, then having an invisible armor stand with the player's nickname above them? This is how nickname plugins on Bukkit do it as far as I know.

I really enjoy using Styled Nicknames, thanks for making it!

**Comment by arnokeesman** [comment]
It's out of scope for this mod, Styled Nameplates has been considered but the Minecraft features didn't work out
Someone has created something for 1.20.2+ called Custom Name Tags which can do what you're looking for, just without the armor stands
