### ISSUE TITLE
Nickname format permission checks fail for unkown reason

### ISSUE THREAD

**Issue by Zeklandia** [Patbox/StyledNicknames#2]
Several users on our server have run into this issue. If they set their nickname with `/nick` or `/nickname`, and it includes a formatting tag (e.g., `<blue>`), their nickname will appear correctly in game until they disconnect, but will render incorrectly when they reconnect (e.g., `<blue>Nick` will appear as `Nick` (in blue text) but after disconnecting it will become `<blue>Nick` with no formatting). However, setting their nicknames with `/styled-nicknames` works as expected.

I found that when the players set their own nicknames with `/nick`/`/nickname`, their `player-mod-data/[UUID]/general.dat` file would have `stylednicknames:permission` set to `1`. When an operator set their nickname with `/styled-nicknames`, that value would be `0`. I double-checked, and the players who have permission to set their nickname (`stylednicknames.use`) also have the formatting tags they tried to use (stylednicknames.format.*`). So, somehow the permissions check on formatting tags succeeds before they log off, but fails once they reconnect.

I was not able to reproduce this issue in my offline tests, even with the exact same mods, datapacks, and configurations.

**Comment by Zeklandia** [comment]
This issue happens on both 1.0.1 and 1.0.2. The permissions plugin we use is LuckPerms, but like I said, I haven't been able to reproduce this outside of the server itself, so I can't say if LuckPerms or any other plugin is causing the issue.

Would it be possible to get a version of 1.0.2 with some additional logging around [line 78](https://github.com/Patbox/StyledNicknames/blob/8d2b430769911bc806904d9f8f6482e2ae244ede/src/main/java/eu/pb4/stylednicknames/mixin/ServerPlayNetworkHandlerMixin.java#L78)?

**Comment by Patbox** [comment]
Weird. I tlooks like luckperms didn't load permission data for players? I will fix that through (most likely by storing parsed nicknames)
