### ISSUE TITLE
Nicknames have a red ~ prefix

### ISSUE THREAD

**Issue by Entropy159** [Patbox/StyledNicknames#21]
I have edited the config to remove the prefix, but it still shows a red ~ before the nickname. I don't know what could be causing this. Is it something I did wrong?

**Comment by arnokeesman** [comment]
2 nickname mods
you're setting nicknames using EssentialCommands (red tilde was the giveaway)
you can disable its nickname functionality in /config/essentialcommands.properties, option is something along the lines of "enable_nick"

**Comment by Entropy159** [comment]
Thanks! I got it working.
