### ISSUE TITLE
Team Prefix doesn't show in player list when a nick is set but is shown in chat

### ISSUE THREAD

**Issue by joeyak** [Patbox/StyledNicknames#4]
I was wondering if it would be possible to show the team prefix/suffix in the player list like it does in the chat window.

White name does not have a nick and colored name does not have a team prefix (we're on the same team)
![image](https://user-images.githubusercontent.com/27922090/149250748-ca2a41c7-efcb-4ec0-be2c-fdc3749a781a.png)

Colored name does have a team prefix in chat
![image](https://user-images.githubusercontent.com/27922090/149250815-2f2b1786-9ca8-413a-8a9c-a1716c9e03cb.png)

**Comment by zachthedev** [comment]
I am having this issue too. Would it also be possible to change the players nickname color based on their team color? I have an afk datapack that changes the player name color to grey and adds a suffix.
And then reset their team, so  that they would use the nickname color.
@Patbox

**Comment by Patbox** [comment]
Because of how it's implemented, it's kinda tricky. You could hovewer workaround it by disabling the list override in styled nicknames and use styled player list instead
