### ISSUE TITLE
Display name not changing by chat and player list does

### ISSUE THREAD

**Issue by t0mtee** [Patbox/StyledNicknames#5]

**Comment by Patbox** [comment]
More info maybe? What mods do you use. Also whats your config

**Comment by t0mtee** [comment]
> More info maybe? What mods do you use. Also whats your config

sorry for the undetailed response, i was busy at the time.
[Config](https://pastebin.com/eU3hX1jd)
modlist:
![OnPaste 20220403-213951](https://user-images.githubusercontent.com/33041004/161447642-a6730df7-6804-4689-979e-eee5ea5a479c.png)
![Capture](https://user-images.githubusercontent.com/33041004/161447757-22e51557-96c7-441e-8e31-39daf6675e02.PNG)
