### ISSUE TITLE
Command fails "invalid placeholder"

### ISSUE THREAD

**Issue by PeterEhses** [Patbox/StyledNicknames#6]
On the default config, with the current release, using either /nick .. or /nickname set someName, a given player name name is changed to "#[Invalid Placeholder!]" instead of the correct name. This is without any formatting in the nickname.
 
![image](https://user-images.githubusercontent.com/46418699/173198882-3d4ee8be-8016-4dc4-966d-0f61d702c943.png)

Wen trying the same command through the server console, the following error is thrown:
[19:40:11] [Server thread/INFO]: An unexpected error occurred trying to execute that command

**Comment by 42willow** [comment]
This also happens to me

**Comment by l4ssc** [comment]
Update to version 1.1.1, for some reason 1.1.0 is listed as the main version on Modrinth.
