### ISSUE TITLE
Add /bio

### ISSUE THREAD

**Issue by sylv256** [Patbox/StyledNicknames#9]
It would be really cool to have a custom formatted `/bio` command like Drogtor. As Drogtor is now in feature freeze (see https://github.com/unascribed/Drogtor/issues/14), it is now obsolete in favor of this mod. I would love to see a `/bio` command in this mod for pronouns and player bios, especially because Switchy now supports this mod and this mod has such extensive styling features.

**Comment by Patbox** [comment]
It's little out of scope for this mod. For pronouns there is https://modrinth.com/mod/player-pronouns

**Comment by sylv256** [comment]
I guess I'll have to make a separate mod for this, then. You're using PlaceholderAPI for parsing the custom text formatting, right?

**Comment by Patbox** [comment]
Yep, it only uses that for parsing

**Comment by sylv256** [comment]
I will close this issue then. Maybe I'll work on another mod for a `/bio` command.

**Comment by Patbox** [comment]
Feel free to later link it there, I can see people finding it useful
